//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skhedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActTable
    {
        public string jenisAct { get; set; }
        public string namaAct { get; set; }
        public System.DateTime waktuAct { get; set; }
        public string deskAct { get; set; }
        public int idAct { get; set; }
    }
}
