//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skhedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActDailyTable
    {
        public string jenisDact { get; set; }
        public string namaDact { get; set; }
        public string waktuDact { get; set; }
        public string deskDact { get; set; }
        public int idDact { get; set; }
    }
}
